TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/CCD100Sup/devCCD100.proto
DATA += devCCD100.proto

#=======================================
include $(TOP)/configure/RULES
