TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devCCD100.proto devCCD100_mk3.proto

#=======================================
include $(TOP)/configure/RULES
